### ISSUE TITLE
Hisotgram not appearing.

### ISSUE THREAD

**Issue by mnabilurrehman** [DJI-Mobile-SDK-Tutorials/Android-UXSDKDemo#14]
I have build the UXSDKDemo. Everything is working fine.

When i go to menu > setting > histogram

Histogram is not appearing

I tried it multiple times under different environments.

**Comment by mnabilurrehman** [comment]
Link to see video demo: https://drive.google.com/open?id=1-3WLsogmC5kqJvfvOwS9ukyg_j5-c146

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/28470'>Zendesk ticket #28470</a>:<br><br>Thanks for reporting this -we'll work on fixing this in the tutorial demo.  In the meanwhile, if you go to the official UXSDK Android Sample Code, you'll see that the histogram works - please reference this as the official sample: https://github.com/dji-sdk/Mobile-UXSDK-Android

Lisa Fedane
DJI Developer Support

**Comment by mnabilurrehman** [comment]
Thank you  @dji-dev  team!

I have implemented this in xml:

  <dji.ux.widget.HistogramWidget
        android:layout_width="400dp"
        android:layout_height="350dp" />

and the issue is resolved now.

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/28470'>Zendesk ticket #28470</a>:<br><br>Request #28481 "UXSDKDemo" was closed and merged into this request. Last comment in request #28481:

Hi Nabil,

Thank you for contacting DJI Developer Support and reporting this issue.  I'm looking into this now and will reach back out to you shortly.

Best,

Lisa Fedane
DJI Developer Support
