### ISSUE TITLE
Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference

### ISSUE THREAD

**Issue by iamzhongjian** [DJI-Mobile-SDK-Tutorials/Android-UXSDKDemo#15]
DemoApplication里registerApp(getApplicationContext(), mDJISDKManagerCallback)，这里mDJISDKManagerCallback为null，mDJISDKManagerCallback是在后面new的，请问是SDK内通过其他方式调用了registerApp吗？当我先new mDJISDKManagerCallback再registerApp(getApplicationContext(), mDJISDKManagerCallback)，这时候一直报错Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30277'>Zendesk ticket #30277</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
理论上先new和后new是没有关系的，您的报错应该是出在其他方面，建议您定位下代码。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
