### ISSUE TITLE
UXSDK能不能有像DJI Pilot App中manual flight那样的设置组件（右上角）？

### ISSUE THREAD

**Issue by beerjtu** [DJI-Mobile-SDK-Tutorials/Android-UXSDKDemo#16]
UXSDK能不能有像DJI Pilot App中manual flight那样的设置组件（右上角）？

**Comment by dji-dev** [comment]
Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/32454'>Zendesk ticket #32454</a>:<br><br>您好，请问您具体指的是哪个功能，能否截个图给我们。

**Comment by beerjtu** [comment]
![e9e31e59b8e1fe89dff09f63bdf5920](https://user-images.githubusercontent.com/13231894/75601992-0035b680-5afc-11ea-8041-3d9c03c17850.jpg)
![c57394b0304bd4eae08f33aa3dc7d4e](https://user-images.githubusercontent.com/13231894/75601993-00ce4d00-5afc-11ea-8cac-a3beae14d773.jpg)

**Comment by beerjtu** [comment]
![e9e31e59b8e1fe89dff09f63bdf5920](https://user-images.githubusercontent.com/13231894/75601996-075cc480-5afc-11ea-899f-70c07a41c5a6.jpg)
![c57394b0304bd4eae08f33aa3dc7d4e](https://user-images.githubusercontent.com/13231894/75601997-07f55b00-5afc-11ea-8789-c60667d2c323.jpg)进入DJI Pilot App的手动飞行中，点击右上角的“...”，进入到飞控参数设置， UXSDK中有没有这个控件？

**Comment by dji-dev** [comment]
Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/32454'>Zendesk ticket #32454</a>:<br><br>您好，很抱歉UXSDK没有这样的组件。如果您有这样的需求，请您填写需求收集表单：https://formcrafts.com/a/dji-developer-feedback-cn 。重点说明需求的应用场景以及您的公司背景，我们的工程师会根据您填写的内容进行评估，并决定是否增加这样的功能。
