### ISSUE TITLE
DJISDKManager.SDKManagerCallback onRegister

### ISSUE THREAD

**Issue by natxopedreira** [DJI-Mobile-SDK-Tutorials/Android-UXSDKDemo#23]
Hello

Im trying to run this sample, it builds and compile without any problem but registering methods are never called...

and yes i create an app in my account with the correct package name, platform and put the app key in AndroidManifest and my device has internet connection and i see no related errors in logcat..... what can be the cause???

Thanks

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/43506'>Zendesk ticket #43506</a>:<br><br>Dear Client
Thank you for contacting DJI.

Have you change the applicationId in build.gradle file? I think there are some places you forget to change.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by natxopedreira** [comment]
Hello

Yes i added, but note that in your demo is not done
[https://github.com/DJI-Mobile-SDK-Tutorials/Android-UXSDKDemo/blob/master/UXSDKDemo/app/build.gradle](https://github.com/DJI-Mobile-SDK-Tutorials/Android-UXSDKDemo/blob/master/UXSDKDemo/app/build.gradle)

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/43506'>Zendesk ticket #43506</a>:<br><br>Dear Client
Thank you for contacting DJI.

The demo is completed. How about you don't change anything. Just apply an appkey based on the original package name and see if you can register. It is fine on my side.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by natxopedreira** [comment]
i can ensure that i only put my api key here
[https://github.com/DJI-Mobile-SDK-Tutorials/Android-UXSDKDemo/blob/9c3cd17e9612ad1958df3fe3bdb15e1582452df8/UXSDKDemo/app/src/main/AndroidManifest.xml#L44](https://github.com/DJI-Mobile-SDK-Tutorials/Android-UXSDKDemo/blob/9c3cd17e9612ad1958df3fe3bdb15e1582452df8/UXSDKDemo/app/src/main/AndroidManifest.xml#L44)

I tried also to put applicationId in build.gradle file as i found it on forums.

Tried on two computers  with two different android phones and different android studio versions.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/43506'>Zendesk ticket #43506</a>:<br><br>Dear Client
Thank you for contacting DJI.

Maybe try this demo and see if you can register.
Link：https://github.com/dji-sdk/Mobile-SDK-Android

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
